<?php
/**
 * AI Chatbot Component
 * This component is mainly driven by backend/js/modules/ai.js
 * The HTML is injected dynamically via JavaScript to ensure it's available
 * on all pages that include the main JS bundle.
 */
?>
<!-- AI Chatbot UI Placeholder -->
<!-- The actual UI is generated by backend/js/modules/ai.js -->
<div id="ai-chatbot-root"></div>